#!/bin/bash

sbatch script_10GB.sbatch ./seq_4k/bigbuck_bunny_8bit.y4m ./configs/test8_config.cfg bitrate="1100"
sbatch script_10GB.sbatch ./seq_4k/bigbuck_bunny_8bit.y4m ./configs/test8_config.cfg bitrate="1200"
sbatch script_10GB.sbatch ./seq_4k/bigbuck_bunny_8bit.y4m ./configs/test8_config.cfg bitrate="1300"
sbatch script_10GB.sbatch ./seq_4k/bigbuck_bunny_8bit.y4m ./configs/test8_config.cfg bitrate="1400"
sbatch script_10GB.sbatch ./seq_4k/bigbuck_bunny_8bit.y4m ./configs/test8_config.cfg bitrate="1500"
sbatch script_10GB.sbatch ./seq_4k/bigbuck_bunny_8bit.y4m ./configs/test8_config.cfg bitrate="2000"
sbatch script_10GB.sbatch ./seq_4k/bigbuck_bunny_8bit.y4m ./configs/test8_config.cfg bitrate="3000"
sbatch script_10GB.sbatch ./seq_4k/bigbuck_bunny_8bit.y4m ./configs/test8_config.cfg bitrate="4000"
sbatch script_10GB.sbatch ./seq_4k/bigbuck_bunny_8bit.y4m ./configs/test8_config.cfg bitrate="5000"
sbatch script_10GB.sbatch ./seq_4k/bigbuck_bunny_8bit.y4m ./configs/test8_config.cfg bitrate="6000"
sbatch script_10GB.sbatch ./seq_4k/bigbuck_bunny_8bit.y4m ./configs/test8_config.cfg bitrate="7000"
sbatch script_10GB.sbatch ./seq_4k/bigbuck_bunny_8bit.y4m ./configs/test8_config.cfg bitrate="8000"
sbatch script_10GB.sbatch ./seq_4k/bigbuck_bunny_8bit.y4m ./configs/test8_config.cfg bitrate="10000"
